# Site settings
title:          MarceloCamera
description:    "gerenciamento | tecnologia | flight simulator"
baseurl:        ""
url:            "https://marcelocamera.github.io"

# Google Analytics
google_analytics: UA-164926776-1

# Author
author:
  name:         Marcelo Camera
  url:          https://marcelocamera.github.io
  email:        marcelo.camera@gmail.com

# Social Network
linkedin:       mcamera
twitter:        marcelocamera
instagram:      marcelocamera
medium:         marcelocamera

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         marcelocamera
